name : 07-expressions
run-name : 07 - Using Expressions | DEBUG - ${{ inputs.debug }}
on : 
    push :
    workflow_dispatch :
        inputs:
            debug : 
                type : boolean
                default : false
jobs :
    echo :
        runs-on : ubuntu-latest
        steps:
            - name : Debug is ${{ inputs.debug }} Print start-up data
              if : ${{ inputs.debug }} == "true"
              run : |
                - echo "Triggered by: ${{ github.actor }}"
                - echo "Branch: ${{ github.ref_name }}"
                - echo "Commit SHA: ${{ github.sha }}" 
                - echo "Runner OS: ${{ runner.os }}"
            - name : Debug is ${{ inputs.debug }} Print when triggered from main
              if : ${{ inputs.debug }} == "true" && ${{ github.ref_name }} == "main"
              run : |
                - echo "I was triggered from main"
            - name : Greeting
              run : echo "Hello, world"



                
